name: Desplegar Aplicación Vite/React en Droplet

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias y construir
      run: |
        npm install
        npm run build

    - name: Transferir archivos al servidor
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "dist/*"
        target: "/root/bucket-front/dist/"
        overwrite: true

    - name: Ejecutar comandos en el servidor
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          echo "Despliegue completado correctamente"
          # Aquí puedes reiniciar un servicio, limpiar archivos viejos, etc.
          # Por ejemplo, si usas Nginx o PM2:
          # sudo systemctl restart nginx
          # pm2 restart app-name